import Head from "next/head";
import Image from "next/image";
import { client } from "../../lib/sanity.client";
import Hero from "./components/Hero";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import Layout from "./components/Layout";

// export async function getStaticProps() {
//   const posts = await client.fetch(`*[_type == "post"]`);
//   return {
//     props: {
//       posts,
//     },
//   };
// }

export default function Home({ posts }) {
  // console.log("posts: ", posts);

  return (
    <>
      <Layout />
      <Head>
        <title>Bach Le</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
      </main>
      <Layout />
    </>
  );
}
