import Head from "next/head";
import Hero from "./components/Hero";
import Layout from "./components/Layout";
import { client } from "../../lib/sanity.client";

export async function getStaticProps() {
  const projects = await client.fetch(
    `*[_type == "project"] | order(_createdAt desc)[0...4]`
  );
  return {
    props: {
      projects,
    },
    revalidate: 60,
  };
}

export default function Home({ projects }) {
  return (
    <Layout>
      <Head>
        <title>Bach Le</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero projects={projects} />
      </main>
    </Layout>
  );
}
